name: CI/CD Pipeline for Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        python -m pip install pytest

    - name: Run test
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest test/ -v  # Adjust if tests are in a different folder

  build-and-deploy:
    needs: test # Only if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only on main branch pushes
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug EC2_HOST
      run: |
        echo "EC2_HOST length: ${#EC2_HOST}"
        echo "EC2_HOST (masked): ${{ secrets.EC2_HOST }}"
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        
    - name: Test SSH Connection
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > github_actions_rsa
          chmod 600 github_actions_rsa
          ssh -i github_actions_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo Connected!"


    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: minakmorgan/devops-test-project:latest  # Replace with your Docker Hub username

    - name: Test SSH Connection
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > github_actions_rsa
        chmod 600 github_actions_rsa
        ssh -i github_actions_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo Connected!"

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22

        script: |
          docker pull minakmorgan/devops-test-project:latest
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d --name flask-container -p 80:5000 minakmorgan/devops-test-project:latest